import {t} from './i18n.js';
import {Renderer} from './render.js';
const $=id=>document.getElementById(id);let renderer,worker,paused=false,busy=false,scene=0,id=0,ready=false,lastSim=0,lastWall=performance.now(),rate=0,pendingReset=false;
function fail(message){$('error').hidden=false;$('error').textContent=t(message);$('status').textContent=t('模拟已停止');paused=true;ready=false;$('play').disabled=true;$('step').disabled=true;}
function reset(){if(scene===1){paused=true;$('play').textContent=t('继续');$('status').textContent=t('已暂停');$('rate').textContent='0.00×';}id++;renderer.clearSurface();if(busy){pendingReset=true;return;}busy=true;pendingReset=false;worker.postMessage({type:'reset',scene,side:+$('quality').value,young:+$('stiffness').value,id});renderer.scene=scene;renderer.side=+$('quality').value;lastSim=0;rate=0;$('error').hidden=true;}
function advance(steps){if(!ready||busy)return;busy=true;worker.postMessage({type:'step',steps,young:+$('stiffness').value,id});}
try{renderer=new Renderer($('view'));renderer.snow.onUpdate=triangles=>{document.body.dataset.surfaceTriangles=String(triangles);};renderer.snow.onError=message=>{setView('particles');$('viewNote').textContent=t('雪表面暂时无法生成，已切回粒子视图。');console.error(message);};worker=new Worker('worker.js',{type:'module'});worker.onerror=e=>fail(e.message);worker.onmessage=({data})=>{busy=false;if(data.fatal){fail(data.fatal);return;}if(pendingReset){reset();return;}if(data.id!==id)return;if(data.error){fail(t('模拟遇到无效形变，已停止。请降低刚度后重新开始。'));return;}renderer.upload(data.data);ready=true;for(const k of ['play','reset','step'])$(k).disabled=false;const now=performance.now();if(!data.reset&&data.time>lastSim){const instant=(data.time-lastSim)/((now-lastWall)/1000);rate=.85*rate+.15*instant;}$('time').textContent=data.time.toFixed(4);$('count').textContent=data.count.toLocaleString(document.documentElement.lang);$('rate').textContent=(paused?0:rate).toFixed(2)+'×';lastSim=data.time;lastWall=now;$('status').textContent=paused?t('已暂停'):t('模拟中');document.body.dataset.ready='true';document.body.dataset.simTime=String(data.time);};reset();let lastFrame=performance.now(),budget=0;function frame(now){const delta=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;renderer.draw();if(!paused&&ready){budget=Math.min(.016,budget+delta*(+$('speed').value));if(!busy&&budget>=.0005){const steps=Math.min(24,Math.floor(budget/.0005));budget-=steps*.0005;advance(steps);}}else budget=0;requestAnimationFrame(frame);}requestAnimationFrame(frame);}catch(e){fail(e.message);}
function setView(mode){renderer.setMode(mode);document.body.dataset.view=mode;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));$('particleLegend').hidden=mode==='snow';$('viewNote').textContent=mode==='snow'?t('连续雪表面 · 柔和散射与细颗粒质感'):t('粒子颜色随压实程度变化，便于观察模拟细节');}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('play').onclick=()=>{paused=!paused;$('play').textContent=paused?t('继续'):t('暂停');$('status').textContent=paused?t('已暂停'):t('模拟中');lastWall=performance.now();if(paused) $('rate').textContent='0.00×';};$('step').onclick=()=>{paused=true;$('play').textContent=t('继续');advance(1);};$('reset').onclick=()=>{reset();};$('camera').onclick=()=>{renderer.resetCamera();};$('quality').onchange=reset;$('stiffness').oninput=()=>{$('stiffValue').textContent=(+$('stiffness').value).toLocaleString(document.documentElement.lang);};document.querySelectorAll('[data-scene]').forEach(button=>button.onclick=()=>{scene=+button.dataset.scene;renderer.scene=scene;renderer.resetCamera();document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('selected',b===button));$('sceneLabel').textContent=button.querySelector('span').childNodes[0].textContent;reset();});

