import {t} from './i18n.js';
import {SnowView} from './snow-view.js';
export function program(gl,vs,fs){function compile(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}const p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,vs));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
function normalize(a){let n=Math.hypot(...a);return a.map(x=>x/n);}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}function dot(a,b){return a.reduce((s,x,i)=>s+x*b[i],0);}function mul(a,b){const c=new Float32Array(16);for(let i=0;i<4;i++)for(let j=0;j<4;j++)for(let k=0;k<4;k++)c[j*4+i]+=a[k*4+i]*b[j*4+k];return c;}
export class Renderer{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false});if(!this.gl)throw Error(t('此浏览器无法创建 WebGL 2。请启用硬件加速或使用支持的浏览器。'));this.angle=-.6;this.pitch=.32;this.distance=1.85;this.count=0;this.scene=0;this.side=8;const gl=this.gl;
 this.mode='snow';this.snow=new SnowView(gl,program);
 this.points=program(gl,`#version 300 es
 precision highp float;precision highp int;layout(location=0) in vec3 pos;layout(location=1) in vec2 material;uniform mat4 vp;uniform mat4 view;uniform float height;uniform float radius;uniform int kind;out vec2 state;out float eyeZ;out float worldRadius;void main(){vec3 p=pos;if(kind==1)p.y=.0627;vec4 eye=view*vec4(p,1);gl_Position=vp*vec4(p,1);gl_PointSize=clamp(.5*radius*height/-eye.z,1.,1024.);state=material;eyeZ=eye.z;worldRadius=radius*.5;}`,`#version 300 es
 precision highp float;precision highp int;in vec2 state;in float eyeZ;in float worldRadius;uniform vec2 depthParams;uniform int kind;out vec4 color;void main(){vec2 q=gl_PointCoord*2.-1.;float r=dot(q,q);if(r>1.)discard;gl_FragDepth=gl_FragCoord.z;if(kind==1){color=vec4(.0,.035,.04,.04*(1.-r));return;}vec3 n=vec3(q.x,-q.y,sqrt(1.-r));float surfaceZ=eyeZ+n.z*worldRadius;gl_FragDepth=.5+.5*(depthParams.x*surfaceZ+depthParams.y)/(-surfaceZ);float light=.36+.64*max(0.,dot(n,normalize(vec3(-.4,.7,.8))));vec3 base=state.y>.5?vec3(.99,.69,.43):vec3(.75,.94,.84);if(kind==3)base=vec3(.94,.975,1.);if(kind==2)base=vec3(.17,.41,.46);else if(kind!=3)base=mix(base,vec3(.16,.52,.43),clamp((1.-state.x)*1.8,0.,.75));float spec=pow(max(0.,dot(n,normalize(vec3(-.3,.5,1.)))),28.)*.2;color=vec4(base*light+spec,1);}`);
 this.lines=program(gl,`#version 300 es
 layout(location=0)in vec3 pos;uniform mat4 vp;void main(){gl_Position=vp*vec4(pos,1);}`,`#version 300 es
 precision highp float;precision highp int;uniform vec4 tint;out vec4 color;void main(){color=tint;}`);
 this.dataBuffer=gl.createBuffer();this.pointVao=gl.createVertexArray();gl.bindVertexArray(this.pointVao);gl.bindBuffer(gl.ARRAY_BUFFER,this.dataBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,2,gl.FLOAT,false,20,12);
 const lines=[];for(let i=0;i<=16;i++){let v=.05+i*.9/16;lines.push(.05,.0625,v,.95,.0625,v,v,.0625,.05,v,.0625,.95);}const corners=[[.05,.0625,.05],[.95,.0625,.05],[.95,.0625,.95],[.05,.0625,.95]];for(const p of corners)lines.push(...p,p[0],.92,p[2]);this.lineCount=lines.length/3;this.lineVao=gl.createVertexArray();gl.bindVertexArray(this.lineVao);gl.bindBuffer(gl.ARRAY_BUFFER,gl.createBuffer());gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(lines),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);
 this.sphereVao=gl.createVertexArray();gl.bindVertexArray(this.sphereVao);gl.bindBuffer(gl.ARRAY_BUFFER,gl.createBuffer());gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([.5,.29,.5,1,0]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,2,gl.FLOAT,false,20,12);
 let dragging=false,last;canvas.addEventListener('pointerdown',e=>{dragging=true;last=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(dragging){this.angle-=(e.clientX-last[0])*.006;this.pitch=Math.max(.08,Math.min(1.25,this.pitch+(e.clientY-last[1])*.005));last=[e.clientX,e.clientY];}});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);canvas.addEventListener('wheel',e=>{e.preventDefault();this.distance=Math.max(1.1,Math.min(3.5,this.distance*Math.exp(e.deltaY*.001)));},{passive:false});
 }
 particleSpacing(){return this.scene===1?.044/(this.side<10?2:this.side<12?3:4):(this.scene===0?.24:.32)/this.side;}
 resetCamera(){this.angle=this.scene===1?-.12:-.6;this.pitch=this.scene===1?.18:.32;this.distance=1.85;}
 setMode(mode){this.mode=mode;this.snow.active=mode==='snow';this.snow.dispatch();}
 clearSurface(){this.snow.clear();}
 upload(data){const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,this.dataBuffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);this.count=data.length/5;this.snow.update(data,this.particleSpacing());}
 draw(){const gl=this.gl,c=this.canvas,dpr=Math.min(devicePixelRatio,2),w=Math.round(c.clientWidth*dpr),h=Math.round(c.clientHeight*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h;}gl.viewport(0,0,w,h);gl.clearColor(.033,.105,.127,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);let target=[.5,.4,.5],eye=[target[0]+Math.sin(this.angle)*Math.cos(this.pitch)*this.distance,target[1]+Math.sin(this.pitch)*this.distance,target[2]+Math.cos(this.angle)*Math.cos(this.pitch)*this.distance];let z=normalize(eye.map((v,i)=>v-target[i])),x=normalize(cross([0,1,0],z)),y=cross(z,x);let view=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);let f=1/Math.tan(.7/2),near=.01,far=20,proj=new Float32Array([f*h/w,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]),vp=mul(proj,view);
 if(this.mode==='snow')this.snow.floor(vp);
 gl.useProgram(this.lines);gl.uniformMatrix4fv(gl.getUniformLocation(this.lines,'vp'),false,vp);gl.uniform4f(gl.getUniformLocation(this.lines,'tint'),.13,.26,.28,1);gl.bindVertexArray(this.lineVao);gl.drawArrays(gl.LINES,0,this.lineCount);
 gl.useProgram(this.points);gl.uniformMatrix4fv(gl.getUniformLocation(this.points,'vp'),false,vp);gl.uniformMatrix4fv(gl.getUniformLocation(this.points,'view'),false,view);gl.uniform2f(gl.getUniformLocation(this.points,'depthParams'),proj[10],proj[14]);gl.uniform1f(gl.getUniformLocation(this.points,'height'),h*f);gl.uniform1f(gl.getUniformLocation(this.points,'radius'),this.particleSpacing()*.72);gl.bindVertexArray(this.pointVao);gl.uniform1i(gl.getUniformLocation(this.points,'kind'),1);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawArrays(gl.POINTS,0,this.count);gl.depthMask(true);gl.disable(gl.BLEND);if(this.mode==='snow')gl.uniform1f(gl.getUniformLocation(this.points,'radius'),this.particleSpacing()*.18);gl.uniform1i(gl.getUniformLocation(this.points,'kind'),this.mode==='snow'?3:0);gl.drawArrays(gl.POINTS,0,this.count);
 if(this.mode==='snow')this.snow.draw(vp,eye);
 gl.useProgram(this.points);
 if(this.scene===2){gl.bindVertexArray(this.sphereVao);gl.uniform1f(gl.getUniformLocation(this.points,'radius'),.30);gl.uniform1i(gl.getUniformLocation(this.points,'kind'),2);gl.drawArrays(gl.POINTS,0,1);}
 }
}

